/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.revature;

import com.revature.dao.*;
import com.revature.exceptions.AssignmentPastDueException;
import com.revature.exceptions.NotATeacherException;
import com.revature.models.User;


import java.sql.Date;

public class SchoolManagementDriver {



    public static void main(String[] args) {

    }
}
